<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25418a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25418520>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25418ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2541dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>