<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2533e640>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?descricao=Non-existent%20description&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2533e7f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?descricao=Non-existent%20description&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2533ea00>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?descricao=Non-existent%20description&</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?descricao=Non-existent%20description& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2533ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>