<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538f5b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?preco=0.5&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538f400>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?preco=0.5&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538f460>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?preco=0.5&</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?preco=0.5& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>