{
  "uid" : "fc74c7065acc8021",
  "name" : "Validate user API schema",
  "fullName" : "Schema-Tests.Schemas.Usuarios.TestUsuariosSchema.Validate user API schema",
  "historyId" : "43177f945fb13975f6be143e3f35986f",
  "time" : {
    "start" : 1655220746869,
    "stop" : 1655220747485,
    "duration" : 616
  },
  "status" : "failed",
  "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "flaky" : true,
  "newFailed" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "steps" : [ {
      "name" : "UsuarioKW.Search All Users",
      "time" : {
        "start" : 1655220746870,
        "stop" : 1655220747483,
        "duration" : 613
      },
      "status" : "failed",
      "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "steps" : [ {
        "name" : "BuiltIn.Create Dictionary",
        "time" : {
          "start" : 1655220746870,
          "stop" : 1655220746871,
          "duration" : 1
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ {
          "uid" : "4bdf94aaf5eb4162",
          "name" : "Keyword Log",
          "source" : "4bdf94aaf5eb4162.html",
          "type" : "text/html",
          "size" : 75
        } ],
        "parameters" : [ {
          "name" : "arg1",
          "value" : "content-type=application/json"
        } ],
        "stepsCount" : 0,
        "attachmentsCount" : 1,
        "shouldDisplayMessage" : false,
        "hasContent" : true
      }, {
        "name" : "RequestsLibrary.Create Session",
        "time" : {
          "start" : 1655220746871,
          "stop" : 1655220746872,
          "duration" : 1
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ {
          "uid" : "20f8f6a2c2e128a1",
          "name" : "Keyword Log",
          "source" : "20f8f6a2c2e128a1.html",
          "type" : "text/html",
          "size" : 219
        } ],
        "parameters" : [ {
          "name" : "arg1",
          "value" : "serveRest"
        }, {
          "name" : "arg2",
          "value" : "${BASE_URL}"
        }, {
          "name" : "arg3",
          "value" : "verify=True"
        } ],
        "stepsCount" : 0,
        "attachmentsCount" : 1,
        "shouldDisplayMessage" : false,
        "hasContent" : true
      }, {
        "name" : "RequestsLibrary.GET On Session",
        "time" : {
          "start" : 1655220746872,
          "stop" : 1655220747480,
          "duration" : 608
        },
        "status" : "failed",
        "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "steps" : [ ],
        "attachments" : [ {
          "uid" : "fd004b65ffce3cf7",
          "name" : "Keyword Log",
          "source" : "fd004b65ffce3cf7.html",
          "type" : "text/html",
          "size" : 1228
        } ],
        "parameters" : [ {
          "name" : "arg1",
          "value" : "serveRest"
        }, {
          "name" : "arg2",
          "value" : "/usuarios"
        }, {
          "name" : "arg3",
          "value" : "headers=${headers}"
        }, {
          "name" : "arg4",
          "value" : "expected_status=any"
        } ],
        "stepsCount" : 0,
        "attachmentsCount" : 1,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      }, {
        "name" : "BuiltIn.Log",
        "time" : {
          "start" : 1655220747481,
          "stop" : 1655220747481,
          "duration" : 0
        },
        "status" : "failed",
        "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ {
          "name" : "arg1",
          "value" : "${response}"
        } ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      }, {
        "name" : "BuiltIn.Set Test Variable",
        "time" : {
          "start" : 1655220747482,
          "stop" : 1655220747482,
          "duration" : 0
        },
        "status" : "failed",
        "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ {
          "name" : "arg1",
          "value" : "${response}"
        } ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 5,
      "attachmentsCount" : 3,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "BuiltIn.Should Be Equal As Strings",
      "time" : {
        "start" : 1655220747484,
        "stop" : 1655220747484,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "arg1",
        "value" : "${response.status_code}"
      }, {
        "name" : "arg2",
        "value" : "200"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "JsonValidator.Validate Jsonschema From File",
      "time" : {
        "start" : 1655220747484,
        "stop" : 1655220747484,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "arg1",
        "value" : "${response.json()}"
      }, {
        "name" : "arg2",
        "value" : "${USER_SCHEMA}"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 8,
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "Schema-Tests"
  }, {
    "name" : "suite",
    "value" : "Schemas"
  }, {
    "name" : "subSuite",
    "value" : "Usuarios.TestUsuariosSchema"
  }, {
    "name" : "framework",
    "value" : "robotframework"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "host",
    "value" : "fv-az459-504"
  }, {
    "name" : "thread",
    "value" : "default-40586569-262d-4657-8464-77043a354c14"
  }, {
    "name" : "tag",
    "value" : "@regression"
  }, {
    "name" : "tag",
    "value" : "@schema_tests"
  }, {
    "name" : "tag",
    "value" : "@usuarios"
  }, {
    "name" : "tag",
    "value" : "@regression"
  }, {
    "name" : "tag",
    "value" : "@schema_tests"
  }, {
    "name" : "tag",
    "value" : "@usuarios"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 3,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 4,
        "unknown" : 0,
        "total" : 7
      },
      "items" : [ {
        "uid" : "42865ac6cf5bb2cb",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/9//#testresult/42865ac6cf5bb2cb",
        "status" : "passed",
        "time" : {
          "start" : 1655219658464,
          "stop" : 1655219658559,
          "duration" : 95
        }
      }, {
        "uid" : "dd65e1883de61ff8",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/8//#testresult/dd65e1883de61ff8",
        "status" : "passed",
        "time" : {
          "start" : 1655218426712,
          "stop" : 1655218426858,
          "duration" : 146
        }
      }, {
        "uid" : "6972431e93ef2776",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/7//#testresult/6972431e93ef2776",
        "status" : "passed",
        "time" : {
          "start" : 1655217743048,
          "stop" : 1655217743134,
          "duration" : 86
        }
      }, {
        "uid" : "edff3808e50bc0ec",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/5//#testresult/edff3808e50bc0ec",
        "status" : "failed",
        "statusDetails" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))",
        "time" : {
          "start" : 1655217380340,
          "stop" : 1655217380957,
          "duration" : 617
        }
      }, {
        "uid" : "bb852855a720609",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/4//#testresult/bb852855a720609",
        "status" : "failed",
        "statusDetails" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))",
        "time" : {
          "start" : 1655217086113,
          "stop" : 1655217086731,
          "duration" : 618
        }
      }, {
        "uid" : "ebe8527a13c97a3f",
        "reportUrl" : "https://STC-TEAM-PROJECT.github.io/robot-api-stc/3//#testresult/ebe8527a13c97a3f",
        "status" : "passed",
        "time" : {
          "start" : 1655216676231,
          "stop" : 1655216676255,
          "duration" : 24
        }
      } ]
    },
    "tags" : [ "@usuarios", "@schema_tests", "@regression" ]
  },
  "source" : "fc74c7065acc8021.json",
  "parameterValues" : [ ]
}