{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Product defects",
    "children" : [ {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /carrinhos (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfc7e4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Validate car API schema",
        "uid" : "e57e9cabca58534f",
        "parentUid" : "aa43dcc633a2918b5f561cd6053d25b7",
        "status" : "failed",
        "time" : {
          "start" : 1655220745598,
          "stop" : 1655220746227,
          "duration" : 629
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "aa43dcc633a2918b5f561cd6053d25b7"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfbf84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Validate products API",
        "uid" : "7d4be65dfc205b88",
        "parentUid" : "0654a7f0442f7af4fc7f0d5f55594a42",
        "status" : "failed",
        "time" : {
          "start" : 1655220746241,
          "stop" : 1655220746856,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "0654a7f0442f7af4fc7f0d5f55594a42"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efddfb9d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Validate user API schema",
        "uid" : "fc74c7065acc8021",
        "parentUid" : "efeeafd46b012661dd6be763af266769",
        "status" : "failed",
        "time" : {
          "start" : 1655220746869,
          "stop" : 1655220747485,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "efeeafd46b012661dd6be763af266769"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25527a00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully login",
        "uid" : "f923b3affdaa6751",
        "parentUid" : "839518a7605ca328d73e3cf44e8b0a31",
        "status" : "failed",
        "time" : {
          "start" : 1655220751137,
          "stop" : 1655220751791,
          "duration" : 654
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "839518a7605ca328d73e3cf44e8b0a31"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f254543a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with a non-exists email",
        "uid" : "3b5caf8a501c4087",
        "parentUid" : "19ff20fe46d5545110262d85be676731",
        "status" : "failed",
        "time" : {
          "start" : 1655220751796,
          "stop" : 1655220752412,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "19ff20fe46d5545110262d85be676731"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25467a00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with a non-exists email and password",
        "uid" : "f44ed42af4ab4a0",
        "parentUid" : "d49d88494ac54b3cf537c66b30f9e74d",
        "status" : "failed",
        "time" : {
          "start" : 1655220752417,
          "stop" : 1655220753032,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "d49d88494ac54b3cf537c66b30f9e74d"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253fdf70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with a non-exists password",
        "uid" : "7282e8bfa6401d70",
        "parentUid" : "949b1434e47ddff55c6c2ca59205bea9",
        "status" : "failed",
        "time" : {
          "start" : 1655220753036,
          "stop" : 1655220753652,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "949b1434e47ddff55c6c2ca59205bea9"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25427160>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with an invalid email",
        "uid" : "c7667346b474eaba",
        "parentUid" : "831d44fc094dd86e68392a15dedd3469",
        "status" : "failed",
        "time" : {
          "start" : 1655220753656,
          "stop" : 1655220754272,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "831d44fc094dd86e68392a15dedd3469"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253b0e80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with just the blank email",
        "uid" : "ed7dd8e26960e628",
        "parentUid" : "bb535e4b02a5e722acde01692a4bb629",
        "status" : "failed",
        "time" : {
          "start" : 1655220754277,
          "stop" : 1655220754895,
          "duration" : 618
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "bb535e4b02a5e722acde01692a4bb629"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2545f760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with just the blank password",
        "uid" : "9f821bc53e4580cb",
        "parentUid" : "60e96ee71301a0c7e697c3b6125f58e4",
        "status" : "failed",
        "time" : {
          "start" : 1655220754899,
          "stop" : 1655220755516,
          "duration" : 617
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "60e96ee71301a0c7e697c3b6125f58e4"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25587790>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Login with a blank email and password",
        "uid" : "516270837eefe8e3",
        "parentUid" : "35c19a6fb9aaf3bde14c098be7f9f65c",
        "status" : "failed",
        "time" : {
          "start" : 1655220755521,
          "stop" : 1655220756138,
          "duration" : 617
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "35c19a6fb9aaf3bde14c098be7f9f65c"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2541dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating product",
        "uid" : "94bd8d2314cf1932",
        "parentUid" : "b735c328e133243f2a1268db19e1c987",
        "status" : "failed",
        "time" : {
          "start" : 1655220756159,
          "stop" : 1655220756773,
          "duration" : 614
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "b735c328e133243f2a1268db19e1c987"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos/BeeJh5lz3k6kSIzA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25441700>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating product by ID in the URL",
        "uid" : "6f60e2ba8d8471c3",
        "parentUid" : "f3bd1e6928e9e92dffdfd07e407176af",
        "status" : "failed",
        "time" : {
          "start" : 1655220756777,
          "stop" : 1655220757391,
          "duration" : 614
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "f3bd1e6928e9e92dffdfd07e407176af"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?_id=K6leHdftCeOJj8BJ& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2542f790>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating product by ID",
        "uid" : "8f4dab156730a046",
        "parentUid" : "2d5b428df4c035c236cc82cfee109707",
        "status" : "failed",
        "time" : {
          "start" : 1655220757394,
          "stop" : 1655220758010,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "2d5b428df4c035c236cc82cfee109707"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?nome=Samsung%2060%20polegadas& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253e7070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating product by Name",
        "uid" : "16c7cf9fd3cce9c6",
        "parentUid" : "ae1ac23ec7cf6a6130f22fc248e331b6",
        "status" : "failed",
        "time" : {
          "start" : 1655220758014,
          "stop" : 1655220758629,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "ae1ac23ec7cf6a6130f22fc248e331b6"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?nome=Samsung%2060%20polegadas&descricao=Tv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25378460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating product by Description And Name",
        "uid" : "5791caf8f90259b5",
        "parentUid" : "7e59199f63eb3be6d8be781872b417dd",
        "status" : "failed",
        "time" : {
          "start" : 1655220758633,
          "stop" : 1655220759248,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "7e59199f63eb3be6d8be781872b417dd"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos/BeeJh5lz3k6kSIzB (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Unsuccessfully validating product by ID in the URL",
        "uid" : "6dd64adc1f1e2f4",
        "parentUid" : "552b68ec8557bbcb7a089a58e25d6e6c",
        "status" : "failed",
        "time" : {
          "start" : 1655220759251,
          "stop" : 1655220759867,
          "duration" : 616
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "552b68ec8557bbcb7a089a58e25d6e6c"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?nome=Non-existent%20products& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253a8ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Unsuccessfully validating product by Name",
        "uid" : "7320e3630a5a3bbc",
        "parentUid" : "1018b8128214ab88498f996977ea9ba1",
        "status" : "failed",
        "time" : {
          "start" : 1655220759870,
          "stop" : 1655220760485,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "1018b8128214ab88498f996977ea9ba1"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?descricao=Non-existent%20description& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2533ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Unsuccessfully validating product by Description",
        "uid" : "b998d845c904a9bf",
        "parentUid" : "a9d6264546518f908e9307e72842a459",
        "status" : "failed",
        "time" : {
          "start" : 1655220760490,
          "stop" : 1655220761107,
          "duration" : 617
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "a9d6264546518f908e9307e72842a459"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?preco=Non-existent%20price& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25366040>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating that the price must be a number",
        "uid" : "dc67fa9c8d4cc575",
        "parentUid" : "410b412ca55448ea33c8c79266d184e4",
        "status" : "failed",
        "time" : {
          "start" : 1655220761110,
          "stop" : 1655220761727,
          "duration" : 617
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "410b412ca55448ea33c8c79266d184e4"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?preco=0.5& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2538fa00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Successfully validating that the price must be an integer",
        "uid" : "fbdcdfb1a07012ee",
        "parentUid" : "d88c8b34c958b184c9320aa2e682801f",
        "status" : "failed",
        "time" : {
          "start" : 1655220761731,
          "stop" : 1655220762346,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "d88c8b34c958b184c9320aa2e682801f"
    }, {
      "name" : "ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?nome=Samsung%2060%20polegadas&descricao=incorrect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253deca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Unsuccessfully validating product by Description And Name",
        "uid" : "b0228202f5d7522e",
        "parentUid" : "334554963f1c341a9d4ff6537124cc1d",
        "status" : "failed",
        "time" : {
          "start" : 1655220762350,
          "stop" : 1655220762965,
          "duration" : 615
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ ]
      } ],
      "uid" : "334554963f1c341a9d4ff6537124cc1d"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ],
  "name" : "categories"
}