<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd410f3d550>: Failed to establish a new connection: [Errno 111] Connection refused')': /carrinhos</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd410f3d7c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /carrinhos</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd410f3d970>: Failed to establish a new connection: [Errno 111] Connection refused')': /carrinhos</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /carrinhos (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd410f3da90>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>